# docker-compose.prod.yml
version: '3'

services:
  event-app-web:
    container_name: event-app-web-prod
    environment:
      NODE_ENV: production
    command: npm run prod

  event-app-server:
    container_name: event-app-server-prod
    environment:
      NODE_ENV: production
    command: npm run start
