# docker-compose.yml
version: "3"
services:
  carrot-backbone:
    restart: on-failure
    build: ./carrot-backbone/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    command: npm run start
    volumes:
      - .:/carrot-backbone/
      - /carrot-backbone/node_modules

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
