# docker-compose.test.yml
version: '3'

services:
  event-app-web:
    container_name: event-app-web-test
    environment:
      NODE_ENV: test
    command: npm run test

  event-app-server:
    container_name: event-app-server-test
    environment:
      NODE_ENV: test
    command: npm run test
