# docker-compose.yml
version: "3"

services:
  event-app-web:
    restart: on-failure
    build: ./web/
    environment:
      REACT_APP_API_URL: http://${API_HOST}:${API_PORT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/web/
      - /web/node_modules

  event-app-server:
    restart: on-failure
    build: ./server/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/server/
      - /server/node_modules

  postgres:
    image: postgres:11
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
